### ISSUE TITLE
False "PHP switched" message

### ISSUE THREAD

**Issue by daisy1754** [jalendport/switch-php#10]
```
$ switch-php 7.2
PHP switched ✔

You are now using PHP 5.4.45
$ which php
/usr/local/bin/php
$ php --version
PHP 5.4.45 (cli) (built: Nov  9 2017 14:09:48)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

I assume it's because my PHP is not installed via brew. It'd be nice if the tool can show error instead of saying it was successful

**Comment by jalendport** [comment]
> I assume it's because my PHP is not installed via brew.

If this means you're not using Homebrew at all, or you're not using it to install PHP, then `switch-php` is not the tool for you. `switch-php` is not an independent tool for downloading and installing the PHP version you want (e.g. it's not like [`n` for node.js](https://github.com/tj/n)), rather, it piggybacks off of Homebrew to do all the downloading/installing/switching/linking etc.

However, I'm pretty sure that it will throw an error of some sort if you don't have brew installed (haven't tested this but would be the expected behavior). `switch-php` actually verifies that the php version you request is already installed, and so if it's not installed (or I'd imagine if you haven't installed brew), it's going to let you know that said php version needs to `brew install`ed before you can switch to it.

So I'd love to hear more about your setup... If you could let me know more about how you've installed php, as well as maybe the output of `brew list` and `brew services list`, that would be awesome!

**Comment by daisy1754** [comment]
so I already installed php7.2 via brew while waiting for response but I can still repro issue with php7.1

```
 switch-php 7.1
PHP switched ✔

You are now using PHP 7.2.16
```

Here is output of commands you provided:
```
brew list                                
ack			cairo			gettext			jemalloc		libtool			php54			telnet
ansible			cask			giflossy		jpeg			libvpx			php71			terraform
ant			colordiff		glib			kubernetes-cli		libxml2			php@7.1			texi2html
apr			coreutils		gmp			lame			libyaml			php@7.2			tidy-html5
apr-util		curl-openssl		go			libcroco		libzip			pixman			unfs3
arcanist		delve			go-swagger		libev			mercurial		pkg-config		unixodbc
argon2			dep			go@1.7			libevent		nghttp2			postgresql		watch
aspell			dinghy			gobject-introspection	libffi			node			python			watchman
autoconf		emacs			graphite2		libidn			openldap		rbenv			webp
autoenv			ffmpeg			graphviz		libmetalink		openssh			readline		x264
awscli			fontconfig		harfbuzz		libpng			openssl			rtmpdump		xvid
bash-completion		freetds			httpd			libpq			openssl@1.1		ruby			xz
bat			freetype		hub			librsvg			pandoc			ruby-build		yarn
boost			gd			icu4c			libsodium		pango			slackcat		yasm
brotli			gdbm			imagemagick		libssh2			parallel		spdylay			zsh
c-ares			gdk-pixbuf		jansson			libtiff			pcre			sqlite			zsh-completions
> brew services list                                                   
Name       Status  User   Plist
emacs      stopped
httpd      stopped
php@7.1    started myusername /Users/myusername/Library/LaunchAgents/homebrew.mxcl.php@7.1.plist
php@7.2    stopped
postgresql stopped
```

Looks like my path might be messed up? I installed php7.2 via brew but then I needed to add path to brew's php via `export PATH="$(brew --prefix php72)/bin:$PATH"`

**Comment by jalendport** [comment]
Aha, yep I bet it's the PATH that's causing the issues...

So when you install any PHP version via Homebrew, you'll see something akin to the following message:
```
If you need to have php@7.2 first in your PATH run:
  echo 'export PATH="/usr/local/opt/php@7.2/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/php@7.2/sbin:$PATH"' >> ~/.zshrc
```

This is an optional step, but a lot of people end up running it. The problem is that once you've done this, the only way to switch between PHP versions is to remove/edit that line in your `bashrc`/`zshrc` file.

Brew has [a handy `link` command](https://docs.brew.sh/Manpage#ln-link-options-formula) (which `switch-php` makes use of) that manages your versions via symlinks instead of manipulating the PATH. Basically, there's a symlink at `/usr/local/bin/php` that just points to whatever version of PHP you want; you would update it for example via `brew unlink php@7.1 && brew link php@7.2`. This is how `switch-php` does the switching, so if you're manually defining the version you want in your `bashrc`/`zshrc` file, then that's going to override whatever `switch-php` tries to do.

To solve, you'll want to remove any lines in your `bashrc`/`zshrc` file where you are manually adding a PHP version to the PATH and instead make sure `/usr/local/bin` and `/usr/local/sbin` are in your PATH. Btw, if you want to learn more about PATH and how it works, I wrote [an article on the topic](https://medium.com/@jalendport/what-exactly-is-your-shell-path-2f076f02deb4) 😉

**Comment by daisy1754** [comment]
thanks for help!

**Comment by jalendport** [comment]
My pleasure 🙌

**Comment by kwkevinlin** [comment]
I'm running into a similar issue, but because PHP 5.6 was deprecated I had to install it a different way. I used:
```
brew tap exolnet/homebrew-deprecated
brew install php@5.6
```

However, when I do a switch then version it still says 7.3:
```
$ switch-php 5.6 -v                   
 👀  Verifying that Valet is installed...
 🔍  Checking which PHP versions are installed...
 🔀  Switching to php@5.6...
 ==>  Stopping php@5.6...
 ==>  Unlinking php@5.6...
 ==>  Stopping php@7.3...
 ==>  Unlinking php@7.3...
 ==>  Linking php@5.6...
 ==>  Starting php@5.6...
 ✅  PHP switched

You are now using PHP 5.6.40
$ php --version
PHP 7.3.9 (cli) (built: Sep 10 2019 17:45:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
```

Here is my `brew list | grep php`:
```
php
php-cs-fixer
php@5.6
```

And my `brew services list`:
```
Name    Status  User    Plist
php     stopped         
php@5.6 started <username> /Users/<username>/Library/LaunchAgents/homebrew.mxcl.php@5.6.plist
```

I am on macOS Catalina, version 10.15.1.

Any thoughts? Could this be related?

**Comment by kwkevinlin** [comment]
@jalendport Quick bump

**Comment by jalendport** [comment]
Hey @kwkevinlin, can you run `echo $PATH` in your Terminal and post the output in here?

**Comment by kwkevinlin** [comment]
Ah I wonder if that is it since this is a newly formatted computer. Here's the command and output:
```
$ echo $PATH
/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by kwkevinlin** [comment]
@jalendport In case the previous tag didn't go through
