### ISSUE TITLE
Changed formula names in brew

### ISSUE THREAD

**Issue by javian** [jalendport/switch-php#4]
I stumbled across this software when looking through random twitter posts. Since homebrew recently merged all the php formulas in to the core distribution you might want to consider changing the formula names to the new ones.

**Comment by jalendport** [comment]
Hey @javian. Yep I've been keeping my eye on it. Since certain parts of this script are dependent upon Laravel Valet I'm planning on waiting until they release an update that makes Valet compatible with the new PHP formula names before I push a new version of my script.

Thanks for pinging me tho! Cheers 🍻

**Comment by jalendport** [comment]
Updated in v1.1.0
